stages:
- name: Build
  steps:
  - runScriptConfig:
      image: maven:3-openjdk-11
      shellScript: mvn package -DskipTests
- name: Build Docker with DIND
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: docker.dev.folio.org/mod-orders:thunderjet-latest
      pushRemote: true
      registry: docker.dev.folio.org
- name: Deploy
  steps:
  - applyAppConfig:
      catalogTemplate: p-n6zpg:thunderjet-helmcharts-mod-orders
      version: 0.1.32
      answers:
        image.repository: docker.dev.folio.org/mod-orders
        image.tag: thunderjet-latest
        postJob.enabled: true
      targetNamespace: thunderjet
      name: mod-orders
timeout: 60
notification: {}
