package org.folio;

import org.springframework.core.annotation.AliasFor;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Annotation to indicate that test(s) in the class are generated by GitHub Copilot.
 * <br><br>
 * Set <code>value</code> or <code>partiallyGenerated</code> attribute to <code>true</code>
 * if the generated test(s) were significantly modified/altered by the developer.
 */
@Target({ElementType.TYPE, ElementType.METHOD})
@Retention(RetentionPolicy.SOURCE)
public @interface CopilotGenerated {

  @AliasFor("partiallyGenerated")
  boolean value() default false;

  @AliasFor("value")
  boolean partiallyGenerated() default false;

  @AliasFor("model")
  String model() default "";
}
