#%RAML 1.0
title: "Acquisitions units"
baseUri: http://github.com/folio-org/mod-orders
version: v1.1

documentation:
  - title: Acquisitions units
    content: <b>CRUD APIs used to manage acquisitions units.</b>

types:
    acquisitions-unit: !include acq-models/acquisitions-unit/schemas/acquisitions_unit.json
    acquisitions-unit-membership: !include acq-models/acquisitions-unit/schemas/acquisitions_unit_membership.json
    acquisitions-unit-collection: !include acq-models/acquisitions-unit/schemas/acquisitions_unit_collection.json
    acquisitions-unit-membership-collection: !include acq-models/acquisitions-unit/schemas/acquisitions_unit_membership_collection.json
    errors: !include raml-util/schemas/errors.schema
    UUID:
     type: string
     pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$

traits:
    validate: !include raml-util/traits/validation.raml
    pageable:  !include raml-util/traits/pageable.raml
    searchable: !include raml-util/traits/searchable.raml

resourceTypes:
    collection: !include raml-util/rtypes/collection.raml
    collection-item: !include raml-util/rtypes/item-collection.raml

/acquisitions-units:
  /units:
    type:
      collection:
        exampleCollection: !include acq-models/acquisitions-unit/examples/acquisitions_unit_collection.sample
        exampleItem: !include acq-models/acquisitions-unit/examples/acquisitions_unit_post.sample
        schemaCollection: acquisitions-unit-collection
        schemaItem: acquisitions-unit
    post:
      description: Create new acquisitions unit
      is: [validate]
    get:
      description: Get list of acquisitions units. In case client does not specify search criteria by "isDeleted" property, the logic will search for records with "isDeleted==false"
      is: [
        searchable: {description: "with valid searchable fields: for example protectRead", example: "[\"protectRead\", \"false\"]"},
        pageable
      ]
    /{id}:
      uriParameters:
        id:
          description: The UUID of an acquisitions unit
          type: UUID
      type:
        collection-item:
          exampleItem: !include acq-models/acquisitions-unit/examples/acquisitions_unit_get.sample
          schema: acquisitions-unit
      put:
        description: Update acquisitions unit
        is: [validate]
      delete:
        description: In order to avoid reference integrity issues when deleting acquisition units that are assigned to records, the logic implements a "soft delete". Update acquisitions unit setting the "isDeleted" field to true
  /memberships:
    type:
      collection:
        exampleCollection: !include acq-models/acquisitions-unit/examples/acquisitions_unit_membership_collection.sample
        exampleItem: !include acq-models/acquisitions-unit/examples/acquisitions_unit_membership_post.sample
        schemaCollection: acquisitions-unit-membership-collection
        schemaItem: acquisitions-unit-membership
    post:
      description: Create new acquisitions units membership
      is: [validate]
    get:
      description: Get list of acquisitions units memberships
      is: [
        searchable: {description: "with valid searchable fields: for example acquisitionsUnitId", example: "[\"acquisitionsUnitId\", \"57c35c88-625d-4f0e-bc79-d22818d84d1c\"]"},
        pageable
      ]
    /{id}:
      uriParameters:
        id:
          description: The UUID of an acquisitions units membership
          type: UUID
      type:
        collection-item:
          exampleItem: !include acq-models/acquisitions-unit/examples/acquisitions_unit_membership_get.sample
          schema: acquisitions-unit-membership
      put:
        description: Update acquisitions units membership
        is: [validate]
