#%RAML 1.0
title: Bind Pieces
baseUri: https://github.com/folio-org/mod-orders
version: v1
protocols: [ HTTP, HTTPS ]

documentation:
  - title: Orders Business Logic API
    content: <b>API for binding pieces with item for one title</b>

types:
  bind-pieces-collection: !include acq-models/mod-orders/schemas/bindPiecesCollection.json
  receiving-results: !include acq-models/mod-orders/schemas/receivingResults.json

  errors: !include raml-util/schemas/errors.schema
  UUID:
    type: string
    pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$

traits:
  validate: !include raml-util/traits/validation.raml

resourceTypes:
  post-with-200: !include rtypes/post-json-200.raml

/orders/bind:
  displayName: Bind pieces
  description: |
    This endpoint used to bind pieces to one item and connect that item to title.
  type:
    post-with-200:
      requestSchema: bind-pieces-collection
      responseSchema: receiving-results
      requestExample: !include acq-models/mod-orders/examples/bindPiecesCollection.sample
      responseExample: !include acq-models/mod-orders/examples/receivingResults.sample
  is: [validate]
  post:
    description: bind pieces to item and connect that item to title
