#%RAML 1.0
title: Check-in
baseUri: https://github.com/folio-org/mod-orders
version: v1
protocols: [ HTTP, HTTPS ]

documentation:
  - title: Orders Business Logic API
    content: <b>API for checking-in pieces</b>

types:
  checkin-collection: !include acq-models/mod-orders/schemas/checkinCollection.json
  receiving-results: !include acq-models/mod-orders/schemas/receivingResults.json
  errors: !include raml-util/schemas/errors.schema
  UUID:
    type: string
    pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$

traits:
  validate: !include raml-util/traits/validation.raml

resourceTypes:
  post-with-200: !include rtypes/post-json-200.raml

/orders/check-in:
  displayName: Check-in items
  description: Check-in items spanning one or more PO lines
  type:
    post-with-200:
      requestSchema: checkin-collection
      responseSchema: receiving-results
      requestExample: !include acq-models/mod-orders/examples/checkinCollection.sample
      responseExample: !include acq-models/mod-orders/examples/receivingResults.sample
  is: [validate]
  post:
    description: Check-in items spanning one or more po_lines in this order
    queryParameters:
      deleteHoldings:
        displayName: The associated holdings should be removed
        description: The associated holdings should be removed
        type: boolean
        required: false
        example: true
        default: false
