#%RAML 1.0
title: Receiving history
baseUri: https://github.com/folio-org/mod-orders
version: v1
protocols: [ HTTP, HTTPS ]

documentation:
  - title: Orders Business Logic API
    content: <b>API for retriving receiving history</b>

types:
  receiving-history-collection: !include acq-models/mod-orders-storage/schemas/receiving_history_collection.json
  errors: !include raml-util/schemas/errors.schema
  UUID:
    type: string
    pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$

traits:
  pageable: !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  validate: !include raml-util/traits/validation.raml

resourceTypes:
  collection-get: !include rtypes/collection-get-with-json-response.raml

/orders/receiving-history:
  get:
    displayName: Receiving history
    description: Get receiving history matching the provided criteria
    is: [
      pageable,
      searchable: {
        description:
          "With valid searchable fields",
        example:
          "titleOrPackage==Harry Potter AND receiving_status==received sortBy po_line_number"
      },
      validate
    ]
  type:
    collection-get:
      exampleCollection: !include acq-models/mod-orders-storage/examples/receiving_history_collection.sample
      schemaCollection: receiving-history-collection
