#%RAML 1.0
title: Rollover
baseUri: https://github.com/folio-org/mod-orders
version: v1
protocols: [ HTTP, HTTPS ]

documentation:
  - title: Orders Business Logic API
    content: <b>API for running Orders rollover</b>

types:
  ledger-fiscal-year-rollover: !include acq-models/mod-finance/schemas/ledger_fiscal_year_rollover.json
  ledger-fiscal-year-rollover-collection: !include acq-models/mod-finance/schemas/ledger_fiscal_year_rollover_collection.json
  errors: !include raml-util/schemas/errors.schema

traits:
  validate: !include raml-util/traits/validation.raml

resourceTypes:
  post-with-200: !include rtypes/post-json-200.raml

/orders/rollover:
  displayName: Rollover orders
  description: Start Orders rollover process
  post:
    body:
      application/json:
        type: ledger-fiscal-year-rollover
        example:
          strict: false
          value: !include acq-models/mod-finance/examples/ledger_fiscal_year_rollover.sample
    responses:
      204:
        description: "Rollover completed successfully"
      400:
        description: "Bad request, e.g. malformed request body or query parameter. Details of the error (e.g. name of the parameter or line/character number with malformed data) provided in the response."
        body:
          application/json:
            example:
              strict: false
              value: !include raml-util/examples/errors.sample
          text/plain:
            example: |
              "unable to add <<resourcePathName|!singularize>> -- malformed JSON at 13:3"
      500:
        description: "Internal server error, e.g. due to misconfiguration"
        body:
          application/json:
            example:
              strict: false
              value: !include raml-util/examples/errors.sample
          text/plain:
            example: "Internal server error, contact administrator"
