#%RAML 1.0
title: "RoutingList"
baseUri: https://github.com/folio-org/mod-orders
version: v1.0

documentation:
  - title: Routing lists
    content: <b>CRUD API to manage routing lists.</b>

types:
    routing_list: !include acq-models/mod-orders-storage/schemas/routing_list.json
    routing_list_collection: !include acq-models/mod-orders-storage/schemas/routing_list_collection.json
    UUID:
     type: string
     pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$

traits:
    pageable:  !include raml-util/traits/pageable.raml
    searchable: !include raml-util/traits/searchable.raml

resourceTypes:
  collection: !include rtypes/collection-with-json-response.raml
  collection-item: !include rtypes/item-collection-with-json-response.raml

/orders/routing-lists:
  type:
    collection:
      exampleCollection: !include acq-models/mod-orders-storage/examples/routing_list_collection.sample
      exampleItem: !include acq-models/mod-orders-storage/examples/routing_list_get.sample
      schemaCollection: routing_list_collection
      schemaItem: routing_list
  get:
    description: Get routing lists
    is: [
      searchable: {description: "with valid searchable fields: for example routing list", example: "[\"routing_list\", \"ROUTING_LIST\", \"=\"]"},
      pageable
    ]
  post:
    description: Create routing lists

  /{id}/template:
    uriParameters:
      id:
        description: The UUID of a Title
        type: UUID
    get:
      description: Execute mod-template-engine to process templates with replaced token placeholders [update]
