#%RAML 1.0
title: "Titles"
baseUri: https://github.com/folio-org/mod-orders
version: v1.0

documentation:
  - title: Titles
    content: <b>CRUD API to manage Titles.</b>

types:
    title: !include acq-models/mod-orders-storage/schemas/title.json
    title_collection: !include acq-models/mod-orders-storage/schemas/title_collection.json
    UUID:
     type: string
     pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$

# workaround to prevent api-lint errors for FQM vendor extensions
# see https://github.com/folio-org/fqm-tools/blob/main/docs/generation/field-schema.md#raml-validation-errors
annotationTypes:
  fqm-essential:
    type: boolean
  fqm-visibility:
    type: string
  fqm-visible-by-default:
    type: boolean
  fqm-value-getter:
    type: string

traits:
    pageable:  !include raml-util/traits/pageable.raml
    searchable: !include raml-util/traits/searchable.raml

resourceTypes:
    collection: !include raml-util/rtypes/collection.raml
    collection-item: !include raml-util/rtypes/item-collection.raml

/orders/titles:
  type:
    collection:
      exampleCollection: !include acq-models/mod-orders-storage/examples/title_collection.sample
      exampleItem: !include acq-models/mod-orders-storage/examples/title_post.sample
      schemaCollection: title_collection
      schemaItem: title
  get:
    description: Get list of titles
    is: [
      searchable: {description: "with valid searchable fields: for example title", example: "[\"title\", \"TITLE\", \"=\"]"},
      pageable
    ]
  /{id}:
    uriParameters:
      id:
        description: The UUID of a Title
        type: UUID
    type:
      collection-item:
        exampleItem: !include acq-models/mod-orders-storage/examples/title_get.sample
        schema: title
    delete:
      description: Delete a title record
      queryParameters:
        deleteHoldings:
          displayName: The associated holdings should be removed
          type: string
          description: The associated holdings should be removed
          example: "true"
          required: false
      responses:
        204:
          description: Title deleted
        404:
          description: Title not found
        500:
          description: Internal server error
