#%RAML 1.0
title: "Wrapper Pieces"
baseUri: https://github.com/folio-org/mod-orders
version: v4

documentation:
  - title: "Wrapper Pieces"
    content: <b>Read API to manage Wrapper Pieces.</b>

types:
  errors: !include raml-util/schemas/errors.schema
  wrapper_piece: !include acq-models/mod-orders-storage/schemas/wrapper_piece.json
  wrapper_piece_collection: !include acq-models/mod-orders-storage/schemas/wrapper_piece_collection.json
  UUID:
    type: string
    pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$

# workaround to prevent api-lint errors for FQM vendor extensions
# see https://github.com/folio-org/fqm-tools/blob/main/docs/generation/field-schema.md#raml-validation-errors
annotationTypes:
  fqm-essential:
    type: boolean
  fqm-visibility:
    type: string
  fqm-visible-by-default:
    type: boolean
  fqm-value-getter:
    type: string

traits:
  orderable: !include raml-util/traits/orderable.raml
  pageable:  !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml

resourceTypes:
  collection-get: !include raml-util/rtypes/collection-get.raml
  collection-item-get: !include raml-util/rtypes/item-collection-get-with-json-response.raml

/orders/wrapper-pieces:
  type:
    collection-get:
      exampleCollection: !include acq-models/mod-orders-storage/examples/wrapper_piece_collection.sample
      schemaCollection: wrapper_piece_collection
  get:
    description: Get list of Wrapper Pieces
    is: [
      searchable: {description: "with valid searchable fields: for example code", example: "[\"code\", \"MEDGRANT\", \"=\"]"},
      pageable
    ]
  /{id}:
    uriParameters:
      id:
        description: The UUID of a Wrapper Piece
        type: UUID
    type:
      collection-item-get:
        exampleItem: !include acq-models/mod-orders-storage/examples/wrapper_piece_get.sample
        schema: wrapper_piece
